## Application configuration file aurora-cli
## Version: 0.0.5

## Path to sign keys
## keys:
##  - name: {just name key}
##    key: {path to pem file}
##    cert: {path to pem file}
##
keys:
  - name: Regular
    key: /path/to/key.pem
    cert: /path/to/cert.pem

## Devices list
## devices:
##  - ip: {device ip WI-FI or cable connection}
##    port: {optional ssh port which is used to connect to the device, default 22}
##    pass: {password in device for devel-su}
##
devices:
  - ip: 192.168.2.15
    port: 22
    pass: '00000'

## Platform SDK links
## psdk:
##  - chroot: {link psdk chroot}
##    tooling: {link psdk tooling}
##    targets:
##      - {link target armv7hl}
##      - {link target i486}
##      - {link target ...}
##
psdk:
  ## Platform SDK Testing
  ## 5.0.0.60
  - chroot: https://sdk-repo.omprussia.ru/sdk/installers/5.0.0/PlatformSDK/5.0.0.60/Aurora_OS-5.0.0.60-base-Aurora_Platform_SDK_Chroot-x86_64.tar.bz2
    tooling: https://sdk-repo.omprussia.ru/sdk/installers/5.0.0/PlatformSDK/5.0.0.60/Aurora_OS-5.0.0.60-base-Aurora_SDK_Tooling-x86_64.tar.7z
    targets:
      - https://sdk-repo.omprussia.ru/sdk/installers/5.0.0/PlatformSDK/5.0.0.60/Aurora_OS-5.0.0.60-base-Aurora_SDK_Target-aarch64.tar.7z
      - https://sdk-repo.omprussia.ru/sdk/installers/5.0.0/PlatformSDK/5.0.0.60/Aurora_OS-5.0.0.60-base-Aurora_SDK_Target-x86_64.tar.7z
      - https://sdk-repo.omprussia.ru/sdk/installers/5.0.0/PlatformSDK/5.0.0.60/Aurora_OS-5.0.0.60-base-Aurora_SDK_Target-armv7hl.tar.7z
  ## Platform SDK Public
  ## 4.0.2.303
  - chroot: https://sdk-repo.omprussia.ru/sdk/installers/4.0.2/PlatformSDK/4.0.2.303/Aurora_OS-4.0.2.303-base-Aurora_Platform_SDK_Chroot-i486.tar.bz2
    tooling: https://sdk-repo.omprussia.ru/sdk/installers/4.0.2/PlatformSDK/4.0.2.303/Aurora_OS-4.0.2.303-base-Aurora_SDK_Tooling-i486.tar.bz2
    targets:
      - https://sdk-repo.omprussia.ru/sdk/installers/4.0.2/PlatformSDK/4.0.2.303/Aurora_OS-4.0.2.303-base-Aurora_SDK_Target-armv7hl.tar.bz2
      - https://sdk-repo.omprussia.ru/sdk/installers/4.0.2/PlatformSDK/4.0.2.303/Aurora_OS-4.0.2.303-base-Aurora_SDK_Target-i486.tar.bz2
