## Application configuration file aurora-cli
## Version: 0.0.1

## Path to sign keys
## sign:
##  {type} - extended | regular | system
##    key: {path to pem file}
##    cert: {path to pem file}
sign:
  extended:
    key: /path/to/key.pem
    cert: /path/to/cert.pem
