name: aurora-cli
base: core22
version: '1.3.1'
summary: A collection of scripts to help the Aurora OS developer.
description: Bash scripts combined into one CLI application written in Dart, helping the developer interact with the Aurora OS.

grade: stable
confinement: strict

parts:
  stage:
    plugin: nil
    stage-packages:
      - git
      - git-lfs
      - tar
      - unzip
      - curl
      - bash
  scripts:
    plugin: dump
    source: scripts
    organize:
      '*.sh' : scripts/
  app:
    plugin: dump
    source: aurora_cli/.build
    organize:
      aurora_cli: bin/aurora_cli
  run:
    plugin: dump
    source: bin
    organize:
      run.sh: bin/run.sh
  configuration:
    plugin: dump
    source: .
    organize:
      configuration.yaml: def_configuration.yaml

apps:
  aurora-cli:
    command: bin/run.sh
    plugs:
      - home
      - network
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      GIT_EXEC_PATH: $SNAP/usr/lib/git-core
      GIT_TEMPLATE_DIR: $SNAP/usr/share/git-core/templates
